# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Cadastro_Tela(object):
    def setupUi(self, cadastro):
        cadastro.setObjectName("cadastro")
        cadastro.resize(480, 620)
        cadastro.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.centralwidget = QtWidgets.QWidget(cadastro)
        self.centralwidget.setObjectName("centralwidget")
        self.Title_Cad = QtWidgets.QLabel(self.centralwidget)
        self.Title_Cad.setGeometry(QtCore.QRect(140, 30, 191, 61))
        self.Title_Cad.setStyleSheet("color: #547dbf; font-size: 28pt;")
        self.Title_Cad.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Title_Cad.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Title_Cad.setTextFormat(QtCore.Qt.PlainText)
        self.Title_Cad.setScaledContents(False)
        self.Title_Cad.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_Cad.setObjectName("Title_Cad")
        self.email = QtWidgets.QLabel(self.centralwidget)
        self.email.setGeometry(QtCore.QRect(40, 233, 71, 21))
        self.email.setStyleSheet("color: #547dbf; font-size: 15pt;")
        self.email.setObjectName("email")
        self.usuario_linha = QtWidgets.QLineEdit(self.centralwidget)
        self.usuario_linha.setGeometry(QtCore.QRect(150, 170, 281, 31))
        self.usuario_linha.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 12pt;")
        self.usuario_linha.setObjectName("usuario_linha")
        self.senha = QtWidgets.QLabel(self.centralwidget)
        self.senha.setGeometry(QtCore.QRect(40, 293, 71, 21))
        self.senha.setStyleSheet("color: #547dbf; font-size: 15pt;")
        self.senha.setObjectName("senha")
        self.email_linha = QtWidgets.QLineEdit(self.centralwidget)
        self.email_linha.setGeometry(QtCore.QRect(150, 230, 281, 31))
        self.email_linha.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 12pt;")
        self.email_linha.setObjectName("email_linha")
        self.senha_linha = QtWidgets.QLineEdit(self.centralwidget)
        self.senha_linha.setGeometry(QtCore.QRect(150, 290, 281, 31))
        self.senha_linha.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 12pt;")
        self.senha_linha.setObjectName("senha_linha")
        self.usuario = QtWidgets.QLabel(self.centralwidget)
        self.usuario.setGeometry(QtCore.QRect(40, 173, 91, 21))
        self.usuario.setStyleSheet("color: #547dbf; font-size: 15pt;")
        self.usuario.setObjectName("usuario")
        self.confirmar = QtWidgets.QPushButton(self.centralwidget)
        self.confirmar.setGeometry(QtCore.QRect(280, 370, 151, 51))
        self.confirmar.setStyleSheet("color:#547dbf; \n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.confirmar.setObjectName("confirmar")
        self.voltarBotao = QtWidgets.QPushButton(self.centralwidget)
        self.voltarBotao.setGeometry(QtCore.QRect(10, 60, 31, 28))
        self.voltarBotao.setStyleSheet("color:#547dbf;\n"
"font: 75 13pt \"MS Shell Dlg 2\";")
        self.voltarBotao.setObjectName("voltarBotao")
        cadastro.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(cadastro)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        cadastro.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(cadastro)
        self.statusbar.setObjectName("statusbar")
        cadastro.setStatusBar(self.statusbar)

        self.retranslateUi(cadastro)
        QtCore.QMetaObject.connectSlotsByName(cadastro)

    def retranslateUi(self, cadastro):
        _translate = QtCore.QCoreApplication.translate
        cadastro.setWindowTitle(_translate("cadastro", "MainWindow"))
        self.Title_Cad.setText(_translate("cadastro", "Cadastro"))
        self.email.setText(_translate("cadastro", "Email"))
        self.senha.setText(_translate("cadastro", "Senha"))
        self.usuario.setText(_translate("cadastro", "Usuário"))
        self.confirmar.setText(_translate("cadastro", "CONFIRMAR"))
        self.voltarBotao.setText(_translate("cadastro", "<"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    cadastro = QtWidgets.QMainWindow()
    ui = Cadastro_Tela()
    ui.setupUi(cadastro)
    cadastro.show()
    sys.exit(app.exec_())
