# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Login_Tela(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(480, 620)
        LoginWindow.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(140, 30, 101, 71))
        self.Title.setAutoFillBackground(False)
        self.Title.setStyleSheet("color: #547dbf; font-size: 28pt;")
        self.Title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Title.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Title.setTextFormat(QtCore.Qt.PlainText)
        self.Title.setScaledContents(False)
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.email = QtWidgets.QLabel(self.centralwidget)
        self.email.setGeometry(QtCore.QRect(40, 230, 71, 21))
        self.email.setStyleSheet("color: #547dbf; font-size: 15pt;")
        self.email.setObjectName("email")
        self.senha = QtWidgets.QLabel(self.centralwidget)
        self.senha.setGeometry(QtCore.QRect(40, 290, 71, 21))
        self.senha.setStyleSheet("color: #547dbf; font-size: 15pt;")
        self.senha.setObjectName("senha")
        self.email_linha = QtWidgets.QLineEdit(self.centralwidget)
        self.email_linha.setGeometry(QtCore.QRect(150, 227, 281, 31))
        self.email_linha.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 12pt;")
        self.email_linha.setObjectName("email_linha")
        self.senha_linha = QtWidgets.QLineEdit(self.centralwidget)
        self.senha_linha.setGeometry(QtCore.QRect(150, 287, 281, 31))
        self.senha_linha.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 12pt;")
        self.senha_linha.setObjectName("senha_linha")
        self.confirmarLogin = QtWidgets.QPushButton(self.centralwidget)
        self.confirmarLogin.setGeometry(QtCore.QRect(280, 380, 151, 51))
        self.confirmarLogin.setStyleSheet("color: #547dbf; \n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.confirmarLogin.setObjectName("confirmarLogin")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 330, 191, 16))
        self.label.setStyleSheet("color:rgb(255, 255, 255);font-size: 9pt;")
        self.label.setObjectName("label")
        self.cadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.cadastrar.setGeometry(QtCore.QRect(350, 330, 81, 21))
        self.cadastrar.setStyleSheet("color:#547dbf; \n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.cadastrar.setObjectName("cadastrar")
        self.fecharBota = QtWidgets.QPushButton(self.centralwidget)
        self.fecharBota.setGeometry(QtCore.QRect(160, 400, 101, 28))
        self.fecharBota.setStyleSheet("color:#547dbf;\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.fecharBota.setObjectName("fecharBota")
        self.Title_2 = QtWidgets.QLabel(self.centralwidget)
        self.Title_2.setGeometry(QtCore.QRect(250, 30, 101, 71))
        self.Title_2.setAutoFillBackground(False)
        self.Title_2.setStyleSheet(" font-size: 28pt; color:rgb(54, 54, 54); \n"
"background-color: #547dbf;\n"
"border-radius: 10px;")
        self.Title_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Title_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Title_2.setTextFormat(QtCore.Qt.PlainText)
        self.Title_2.setScaledContents(False)
        self.Title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_2.setObjectName("Title_2")
        self.cadastrar.raise_()
        self.Title.raise_()
        self.email.raise_()
        self.senha.raise_()
        self.email_linha.raise_()
        self.senha_linha.raise_()
        self.confirmarLogin.raise_()
        self.label.raise_()
        self.fecharBota.raise_()
        self.Title_2.raise_()
        LoginWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LoginWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        LoginWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LoginWindow)
        self.statusbar.setObjectName("statusbar")
        LoginWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        self.Title.setText(_translate("LoginWindow", "Task"))
        self.email.setText(_translate("LoginWindow", "Email"))
        self.senha.setText(_translate("LoginWindow", "Senha"))
        self.confirmarLogin.setText(_translate("LoginWindow", "CONFIRMAR"))
        self.label.setText(_translate("LoginWindow", "Sem Conta? Cadastre Já ->"))
        self.cadastrar.setText(_translate("LoginWindow", "CADASTRAR"))
        self.fecharBota.setText(_translate("LoginWindow", "FECHAR"))
        self.Title_2.setText(_translate("LoginWindow", "Hub"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginWindow = QtWidgets.QMainWindow()
    ui = Login_Tela()
    ui.setupUi(LoginWindow)
    LoginWindow.show()
    sys.exit(app.exec_())
