# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'criar_tarefa.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Tarefa(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(697, 607)
        MainWindow.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(30, 0, 81, 51))
        self.Title.setAutoFillBackground(False)
        self.Title.setStyleSheet("color: #547dbf; font-size: 20pt;")
        self.Title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Title.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Title.setTextFormat(QtCore.Qt.PlainText)
        self.Title.setScaledContents(False)
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.Title_2 = QtWidgets.QLabel(self.centralwidget)
        self.Title_2.setGeometry(QtCore.QRect(100, 0, 81, 51))
        self.Title_2.setAutoFillBackground(False)
        self.Title_2.setStyleSheet(" font-size: 20pt; color:rgb(54, 54, 54); \n"
"background-color: #547dbf;\n"
"border-radius: 10px;")
        self.Title_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Title_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Title_2.setTextFormat(QtCore.Qt.PlainText)
        self.Title_2.setScaledContents(False)
        self.Title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_2.setObjectName("Title_2")
        self.title_tarefa = QtWidgets.QLineEdit(self.centralwidget)
        self.title_tarefa.setGeometry(QtCore.QRect(190, 90, 271, 31))
        self.title_tarefa.setStyleSheet("border: 0px;\n"
"background-color: rgb(255, 255, 255);\n"
"font-size: 15px;")
        self.title_tarefa.setObjectName("title_tarefa")
        self.data_tarefa = QtWidgets.QDateEdit(self.centralwidget)
        self.data_tarefa.setGeometry(QtCore.QRect(190, 150, 271, 31))
        self.data_tarefa.setStyleSheet("font-size: 15px;\n"
"background-color: white;")
        self.data_tarefa.setObjectName("data_tarefa")
        self.title = QtWidgets.QLineEdit(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(30, 90, 151, 31))
        self.title.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.title.setStyleSheet("color: #547dbf; font: 20px;")
        self.title.setFrame(False)
        self.title.setReadOnly(True)
        self.title.setObjectName("title")
        self.date = QtWidgets.QLineEdit(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(30, 150, 161, 31))
        self.date.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.date.setStyleSheet("color:#547dbf; font: 20px;")
        self.date.setFrame(False)
        self.date.setReadOnly(True)
        self.date.setObjectName("date")
        self.grupo = QtWidgets.QLineEdit(self.centralwidget)
        self.grupo.setGeometry(QtCore.QRect(30, 210, 161, 31))
        self.grupo.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.grupo.setStyleSheet("color: #547dbf; font: 20px;")
        self.grupo.setFrame(False)
        self.grupo.setReadOnly(True)
        self.grupo.setObjectName("grupo")
        self.cancel = QtWidgets.QPushButton(self.centralwidget)
        self.cancel.setGeometry(QtCore.QRect(130, 520, 171, 28))
        self.cancel.setStyleSheet("color:#547dbf;\n"
"font: 75 13pt \"MS Shell Dlg 2\";")
        self.cancel.setObjectName("cancel")
        self.conf = QtWidgets.QPushButton(self.centralwidget)
        self.conf.setGeometry(QtCore.QRect(400, 520, 171, 28))
        self.conf.setStyleSheet("color:#547dbf;\n"
"font: 75 13pt \"MS Shell Dlg 2\";")
        self.conf.setObjectName("conf")
        self.group_tarefa = QtWidgets.QLineEdit(self.centralwidget)
        self.group_tarefa.setGeometry(QtCore.QRect(190, 210, 261, 31))
        self.group_tarefa.setStyleSheet("font-size: 15px;\n"
"background-color: white;")
        self.group_tarefa.setObjectName("group_tarefa")
        self.status = QtWidgets.QLineEdit(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(30, 280, 161, 31))
        self.status.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.status.setStyleSheet("color: #547dbf; font: 20px;")
        self.status.setFrame(False)
        self.status.setReadOnly(True)
        self.status.setObjectName("status")
        self.status_tarefa = QtWidgets.QComboBox(self.centralwidget)
        self.status_tarefa.setGeometry(QtCore.QRect(190, 280, 221, 31))
        self.status_tarefa.setStyleSheet("font-size: 15px;\n"
"background-color: white;")
        self.status_tarefa.setObjectName("status_tarefa")
        self.status_tarefa.addItem("")
        self.status_tarefa.addItem("")
        self.status_tarefa.addItem("")
        self.descricao_tarefa = QtWidgets.QTextEdit(self.centralwidget)
        self.descricao_tarefa.setGeometry(QtCore.QRect(190, 380, 281, 121))
        self.descricao_tarefa.setStyleSheet("font-size: 15px;\n"
"background-color: white;")
        self.descricao_tarefa.setObjectName("descricao_tarefa")
        self.descricao = QtWidgets.QLineEdit(self.centralwidget)
        self.descricao.setGeometry(QtCore.QRect(30, 390, 151, 31))
        self.descricao.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.descricao.setStyleSheet("color: #547dbf; font: 20px;")
        self.descricao.setFrame(False)
        self.descricao.setReadOnly(True)
        self.descricao.setObjectName("descricao")
        self.prioridade = QtWidgets.QLineEdit(self.centralwidget)
        self.prioridade.setGeometry(QtCore.QRect(30, 330, 161, 31))
        self.prioridade.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.prioridade.setStyleSheet("color: #547dbf; font: 20px;")
        self.prioridade.setFrame(False)
        self.prioridade.setReadOnly(True)
        self.prioridade.setObjectName("prioridade")
        self.prioridade_tarefa = QtWidgets.QComboBox(self.centralwidget)
        self.prioridade_tarefa.setGeometry(QtCore.QRect(190, 330, 221, 31))
        self.prioridade_tarefa.setStyleSheet("font-size: 15px;\n"
"background-color: white;")
        self.prioridade_tarefa.setObjectName("prioridade_tarefa")
        self.prioridade_tarefa.addItem("")
        self.prioridade_tarefa.addItem("")
        self.prioridade_tarefa.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 697, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.status_tarefa.setCurrentIndex(0)
        self.prioridade_tarefa.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Title.setText(_translate("MainWindow", "Task"))
        self.Title_2.setText(_translate("MainWindow", "Hub"))
        self.title.setText(_translate("MainWindow", "Título da Tarefa"))
        self.date.setText(_translate("MainWindow", "Data de Término"))
        self.grupo.setText(_translate("MainWindow", "Grupo"))
        self.cancel.setText(_translate("MainWindow", "CANCELAR"))
        self.conf.setText(_translate("MainWindow", "CONFIMAR"))
        self.status.setText(_translate("MainWindow", "Status"))
        self.status_tarefa.setCurrentText(_translate("MainWindow", "A fazer"))
        self.status_tarefa.setItemText(0, _translate("MainWindow", "A fazer"))
        self.status_tarefa.setItemText(1, _translate("MainWindow", "Fazendo"))
        self.status_tarefa.setItemText(2, _translate("MainWindow", "Concluída"))
        self.descricao_tarefa.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:15px; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.descricao.setText(_translate("MainWindow", "Descrição"))
        self.prioridade.setText(_translate("MainWindow", "Prioridade"))
        self.prioridade_tarefa.setCurrentText(_translate("MainWindow", "Média"))
        self.prioridade_tarefa.setItemText(0, _translate("MainWindow", "Média"))
        self.prioridade_tarefa.setItemText(1, _translate("MainWindow", "Baixa"))
        self.prioridade_tarefa.setItemText(2, _translate("MainWindow", "Alta"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_Tarefa()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
