# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'criar_tarefa.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Tarefa(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 399)
        MainWindow.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(158, 8, 71, 41))
        self.Title.setAutoFillBackground(False)
        self.Title.setStyleSheet("color: rgb(204, 119, 0); font-size: 20pt;")
        self.Title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Title.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Title.setTextFormat(QtCore.Qt.PlainText)
        self.Title.setScaledContents(False)
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.Title_2 = QtWidgets.QLabel(self.centralwidget)
        self.Title_2.setGeometry(QtCore.QRect(233, 2, 81, 51))
        self.Title_2.setAutoFillBackground(False)
        self.Title_2.setStyleSheet(" font-size: 20pt; color:rgb(54, 54, 54); \n"
"background-color: rgb(204, 119, 0);\n"
"border-radius: 10px;")
        self.Title_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Title_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Title_2.setTextFormat(QtCore.Qt.PlainText)
        self.Title_2.setScaledContents(False)
        self.Title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_2.setObjectName("Title_2")
        self.title_text = QtWidgets.QLineEdit(self.centralwidget)
        self.title_text.setGeometry(QtCore.QRect(190, 90, 271, 31))
        self.title_text.setStyleSheet("border: 0px;\n"
"background-color: rgb(255, 255, 255);")
        self.title_text.setObjectName("title_text")
        self.data_ed = QtWidgets.QDateEdit(self.centralwidget)
        self.data_ed.setGeometry(QtCore.QRect(190, 160, 271, 31))
        self.data_ed.setObjectName("data_ed")
        self.title_taf = QtWidgets.QLineEdit(self.centralwidget)
        self.title_taf.setGeometry(QtCore.QRect(20, 90, 151, 31))
        self.title_taf.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.title_taf.setStyleSheet("color: rgb(204, 119, 0); font: 20px;")
        self.title_taf.setFrame(False)
        self.title_taf.setReadOnly(True)
        self.title_taf.setObjectName("title_taf")
        self.date = QtWidgets.QLineEdit(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(20, 160, 161, 31))
        self.date.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.date.setStyleSheet("color: rgb(204, 119, 0); font: 20px;")
        self.date.setFrame(False)
        self.date.setReadOnly(True)
        self.date.setObjectName("date")
        self.grupo = QtWidgets.QLineEdit(self.centralwidget)
        self.grupo.setGeometry(QtCore.QRect(20, 230, 161, 31))
        self.grupo.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.grupo.setStyleSheet("color: rgb(204, 119, 0); font: 20px;")
        self.grupo.setFrame(False)
        self.grupo.setReadOnly(True)
        self.grupo.setObjectName("grupo")
        self.cancel = QtWidgets.QPushButton(self.centralwidget)
        self.cancel.setGeometry(QtCore.QRect(30, 310, 171, 28))
        self.cancel.setStyleSheet("color:rgb(204, 119, 0);\n"
"font: 75 13pt \"MS Shell Dlg 2\";")
        self.cancel.setObjectName("cancel")
        self.conf = QtWidgets.QPushButton(self.centralwidget)
        self.conf.setGeometry(QtCore.QRect(280, 310, 171, 28))
        self.conf.setStyleSheet("color:rgb(204, 119, 0);\n"
"font: 75 13pt \"MS Shell Dlg 2\";")
        self.conf.setObjectName("conf")
        self.group_name = QtWidgets.QLineEdit(self.centralwidget)
        self.group_name.setGeometry(QtCore.QRect(190, 230, 261, 31))
        self.group_name.setObjectName("group_name")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Title.setText(_translate("MainWindow", "Task"))
        self.Title_2.setText(_translate("MainWindow", "Hub"))
        self.title_taf.setText(_translate("MainWindow", "Título da Tarefa"))
        self.date.setText(_translate("MainWindow", "Data de Término"))
        self.grupo.setText(_translate("MainWindow", "Grupo"))
        self.cancel.setText(_translate("MainWindow", "CANCELAR"))
        self.conf.setText(_translate("MainWindow", "CONFIMAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_Tarefa()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
